version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      raskat_net:
        ipv4_address: 172.20.0.10
  ui:
    build: ./ui
    networks:
      raskat_net:
        ipv4_address: 172.20.0.11
  backend:
    build: ./backend
    networks:
      raskat_net:
        ipv4_address: 172.20.0.12
networks:
  raskat_net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
